"""Bridges the AudioCodes Bot API to the Deepgram Voice Agent API."""

from .bridge import DeepgramBridge
from .types import (
    # Configuration
    BridgeConfig,
    DeepgramAgentConfig,
    DeepgramConfig,
    DeepgramFunction,
    DeepgramFunctionParameters,
    DeepgramFunctionParameterProperty,
    AudioCodesMediaFormat,
    # Bridge events
    SessionStartEvent,
    InboundActivityEvent,
    ConversationTextEvent,
    UserStartedSpeakingEvent,
    AgentThinkingEvent,
    AgentAudioDoneEvent,
    FunctionCall,
    FunctionCallRequestEvent,
    PromptUpdatedEvent,
    SpeakUpdatedEvent,
    ThinkUpdatedEvent,
    WarningEvent,
    SessionEndEvent,
    SessionEndReason,
    BridgeErrorEvent,
    # AudioCodes control-message wire types
    SessionInitiateMessage,
    # AudioCodes activity wire types
    AudioCodesBaseActivity,
    AudioCodesEventActivity,
    AudioCodesEventName,
    TransferActivityParams,
    PlayUrlActivityParams,
    SendDtmfActivityParams,
    CallRecordingActivityParams,
)

__all__ = [
    "DeepgramBridge",
    "BridgeConfig",
    "DeepgramAgentConfig",
    "DeepgramConfig",
    "DeepgramFunction",
    "DeepgramFunctionParameters",
    "DeepgramFunctionParameterProperty",
    "AudioCodesMediaFormat",
    "SessionStartEvent",
    "InboundActivityEvent",
    "ConversationTextEvent",
    "UserStartedSpeakingEvent",
    "AgentThinkingEvent",
    "AgentAudioDoneEvent",
    "FunctionCall",
    "FunctionCallRequestEvent",
    "PromptUpdatedEvent",
    "SpeakUpdatedEvent",
    "ThinkUpdatedEvent",
    "WarningEvent",
    "SessionEndEvent",
    "SessionEndReason",
    "BridgeErrorEvent",
    "SessionInitiateMessage",
    "AudioCodesBaseActivity",
    "AudioCodesEventActivity",
    "AudioCodesEventName",
    "TransferActivityParams",
    "PlayUrlActivityParams",
    "SendDtmfActivityParams",
    "CallRecordingActivityParams",
]
